---
version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Sao_Paulo
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /var/lib/docker/volumes/overseerr/config:/app/config
    restart: unless-stopped
