version: "3.7"

services:
  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/lib/docker/volumes/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/lib/docker/volumes/caddy/site:/srv
      - /var/lib/docker/volumes/caddy/_data:/data
      - /var/lib/docker/volumes/caddy/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
volumes:
  caddy:
    external: true
