version: "3.7"

services:
  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/lib/docker/volumes/Caddyfile:/etc/caddy/Caddyfile
      - /var/lib/docker/volumes/site:/srv
      - ./_data:/data
      - ./config:/config
volumes:
  caddy:
    external: true
