version: "2.1"
services:
  netboot-xyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netboot-xyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      # To get the latest version of menu comment the following line
      #- MENU_VERSION=1.9.9 #optional
      - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - /var/lib/docker/volumes/netboot-xyz/config:/config
      - /var/lib/docker/volumes/netboot-xyz/assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped
