---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3100:3100
    env_file: .env
    volumes:
      - /var/lib/docker/volumes/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    enviroment:
      PUID: $PUID
      PGID: $PGID
