version: "3.7"

services:
  xteve:
    image: alturismo/xteve:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "34400:34400"
    volumes:
      - /var/lib/docker/volumes/xteve/:/xteve:rw
      - /var/lib/docker/volumes/xteve/data/.xteve:/root/.xteve:rw
      - /var/lib/docker/volumes/xteve/config/:/config:rw
      #- /var/lib/docker/volumes/xteve/guide2go/:/guide2go:rw
      #- /var/lib/docker/volumes/xteve/playlists/:/playlists:rw
      - /tmp/xteve/:/tmp/xteve:rw
    restart: unless-stopped
