#https://github.com/janeczku/calibre-web?tab=readme-ov-file
---
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Sao_Paulo
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /var/lib/docker/volumes/calibre-web/config:/config
      #- /var/lib/docker/volumes/calibre-web/metadata.db:/config/metadata.db
      #NAS-Proxmox /srv/media/livros
      - /srv/livros/calibre:/books
      - /srv/livros/calibre/metadata.db:/books/metadata.db
    ports:
      - 8083:8083
    restart: unless-stopped